# https://docs.docker.com/go/compose-spec-reference/

# Create server service
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
    volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules

